apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: swish-ci
  namespace: argo
spec:
  entrypoint: ci-pipeline
  arguments:
    parameters:
      - name: target
        value: all
        enum:
          - all
          - python3
          - python2
          - r
  volumes:
    - name: docker-config
      secret:
        secretName: dockerhub-credentials
        items:
          - key: .dockerconfigjson
            path: config.json
    - name: git-secret
      secret:
        secretName: github-credentials
    - name: workspace
      persistentVolumeClaim:
        claimName: swish-workspace

  templates:
    # --- Main DAG ---
    - name: ci-pipeline
      dag:
        tasks:
          - name: checkout
            template: git-checkout

          # Python 3: build → scan
          - name: build-python3
            template: build-and-push
            dependencies: [checkout]
            when: "'{{workflow.parameters.target}}' == 'all' || '{{workflow.parameters.target}}' == 'python3'"
            arguments:
              parameters:
                - name: image-name
                  value: swish-python3
                - name: context
                  value: docker/python3

          - name: scan-python3
            template: trivy-scan
            dependencies: [build-python3]
            when: "'{{workflow.parameters.target}}' == 'all' || '{{workflow.parameters.target}}' == 'python3'"
            arguments:
              parameters:
                - name: image
                  value: cthomaspdx1/swish-python3:latest
                - name: target
                  value: python3

          # Python 2: build → scan
          - name: build-python2
            template: build-and-push
            dependencies: [checkout]
            when: "'{{workflow.parameters.target}}' == 'all' || '{{workflow.parameters.target}}' == 'python2'"
            arguments:
              parameters:
                - name: image-name
                  value: swish-python2
                - name: context
                  value: docker/python2

          - name: scan-python2
            template: trivy-scan
            dependencies: [build-python2]
            when: "'{{workflow.parameters.target}}' == 'all' || '{{workflow.parameters.target}}' == 'python2'"
            arguments:
              parameters:
                - name: image
                  value: cthomaspdx1/swish-python2:latest
                - name: target
                  value: python2

          # R: build → scan
          - name: build-r
            template: build-and-push
            dependencies: [checkout]
            when: "'{{workflow.parameters.target}}' == 'all' || '{{workflow.parameters.target}}' == 'r'"
            arguments:
              parameters:
                - name: image-name
                  value: swish-r
                - name: context
                  value: docker/r

          - name: scan-r
            template: trivy-scan
            dependencies: [build-r]
            when: "'{{workflow.parameters.target}}' == 'all' || '{{workflow.parameters.target}}' == 'r'"
            arguments:
              parameters:
                - name: image
                  value: cthomaspdx1/swish-r:latest
                - name: target
                  value: r

          # Generate CVE remediation reports
          - name: generate-report-python3
            template: generate-report
            dependencies: [scan-python3]
            when: "'{{workflow.parameters.target}}' == 'all' || '{{workflow.parameters.target}}' == 'python3'"
            arguments:
              parameters:
                - name: target
                  value: python3
                - name: image
                  value: cthomaspdx1/swish-python3:latest

          - name: generate-report-python2
            template: generate-report
            dependencies: [scan-python2]
            when: "'{{workflow.parameters.target}}' == 'all' || '{{workflow.parameters.target}}' == 'python2'"
            arguments:
              parameters:
                - name: target
                  value: python2
                - name: image
                  value: cthomaspdx1/swish-python2:latest

          - name: generate-report-r
            template: generate-report
            dependencies: [scan-r]
            when: "'{{workflow.parameters.target}}' == 'all' || '{{workflow.parameters.target}}' == 'r'"
            arguments:
              parameters:
                - name: target
                  value: r
                - name: image
                  value: cthomaspdx1/swish-r:latest

          # Commit all reports back to repo
          - name: commit-reports
            template: commit-reports
            dependencies: [generate-report-python3, generate-report-python2, generate-report-r]

          # Trigger ArgoCD refresh via Argo Events webhook (per target)
          - name: trigger-deploy-python3
            template: trigger-deploy
            dependencies: [scan-python3]
            when: "'{{workflow.parameters.target}}' == 'all' || '{{workflow.parameters.target}}' == 'python3'"
            arguments:
              parameters:
                - name: target
                  value: python3

          - name: trigger-deploy-python2
            template: trigger-deploy
            dependencies: [scan-python2]
            when: "'{{workflow.parameters.target}}' == 'all' || '{{workflow.parameters.target}}' == 'python2'"
            arguments:
              parameters:
                - name: target
                  value: python2

          - name: trigger-deploy-r
            template: trigger-deploy
            dependencies: [scan-r]
            when: "'{{workflow.parameters.target}}' == 'all' || '{{workflow.parameters.target}}' == 'r'"
            arguments:
              parameters:
                - name: target
                  value: r

    # --- Git Checkout ---
    - name: git-checkout
      container:
        image: alpine/git:latest
        command: [sh, -c]
        args:
          - |
            rm -rf /workspace/src
            GIT_USER=$(cat /git-secret/username)
            GIT_PASS=$(cat /git-secret/password)
            git clone https://${GIT_USER}:${GIT_PASS}@github.com/cthomaspdx/swish.git /workspace/src
        volumeMounts:
          - name: workspace
            mountPath: /workspace
          - name: git-secret
            mountPath: /git-secret
            readOnly: true

    # --- Build & Push ---
    - name: build-and-push
      inputs:
        parameters:
          - name: image-name
          - name: context
      container:
        image: gcr.io/kaniko-project/executor:latest
        args:
          - --context=/workspace/src/{{inputs.parameters.context}}
          - --destination=cthomaspdx1/{{inputs.parameters.image-name}}:latest
          - --cache=true
          - --cache-repo=cthomaspdx1/kaniko-cache
          - --single-snapshot
          - --compressed-caching=false
        resources:
          requests:
            memory: 2Gi
            cpu: 500m
          limits:
            memory: 4Gi
        volumeMounts:
          - name: workspace
            mountPath: /workspace
          - name: docker-config
            mountPath: /kaniko/.docker

    # --- Trivy Scan ---
    - name: trivy-scan
      inputs:
        parameters:
          - name: image
          - name: target
      container:
        image: aquasec/trivy:latest
        command: [sh, -c]
        args:
          - |
            mkdir -p /workspace/reports
            trivy image --severity CRITICAL,HIGH --exit-code 0 --format json --output /workspace/reports/{{inputs.parameters.target}}.json "{{inputs.parameters.image}}"
            trivy image --severity CRITICAL,HIGH --exit-code 0 --format table "{{inputs.parameters.image}}"
        volumeMounts:
          - name: workspace
            mountPath: /workspace

    # --- Generate CVE Remediation Report ---
    - name: generate-report
      inputs:
        parameters:
          - name: target
          - name: image
      container:
        image: python:3-alpine
        command: [python3, -c]
        args:
          - |
            import json, datetime, os

            target = "{{inputs.parameters.target}}"
            image = "{{inputs.parameters.image}}"
            json_path = f"/workspace/reports/{target}.json"
            docs_dir = "/workspace/src/docs"
            os.makedirs(docs_dir, exist_ok=True)
            md_path = f"{docs_dir}/{target}-cve-remediation.md"

            with open(json_path) as f:
                data = json.load(f)

            vulns = []
            for result in data.get("Results", []):
                for v in result.get("Vulnerabilities", []):
                    vulns.append({
                        "id": v.get("VulnerabilityID", ""),
                        "pkg": v.get("PkgName", ""),
                        "installed": v.get("InstalledVersion", ""),
                        "fixed": v.get("FixedVersion", ""),
                        "severity": v.get("Severity", ""),
                        "title": v.get("Title", ""),
                    })

            scan_date = datetime.datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")
            lines = [f"# CVE Remediation Report: {target}", ""]
            lines.append(f"**Image:** `{image}`  ")
            lines.append(f"**Scan Date:** {scan_date}  ")
            lines.append(f"**Scanner:** Trivy")
            lines.append("")

            if not vulns:
                lines.append("No CRITICAL or HIGH vulnerabilities found.")
            else:
                critical = [v for v in vulns if v["severity"] == "CRITICAL"]
                high = [v for v in vulns if v["severity"] == "HIGH"]
                has_fix = [v for v in vulns if v["fixed"]]

                lines.append("## Summary")
                lines.append("")
                lines.append("| Severity | Count |")
                lines.append("|----------|-------|")
                lines.append(f"| CRITICAL | {len(critical)} |")
                lines.append(f"| HIGH | {len(high)} |")
                lines.append(f"| **Total** | **{len(vulns)}** |")
                lines.append(f"| With fix available | {len(has_fix)} |")
                lines.append("")

                for sev, sev_vulns in [("CRITICAL", critical), ("HIGH", high)]:
                    if not sev_vulns:
                        continue
                    lines.append(f"## {sev} Vulnerabilities")
                    lines.append("")
                    lines.append("| CVE ID | Package | Installed | Fixed | Title |")
                    lines.append("|--------|---------|-----------|-------|-------|")
                    for v in sev_vulns:
                        fixed = v["fixed"] if v["fixed"] else "—"
                        title = v["title"][:80] if v["title"] else "—"
                        lines.append(f"| {v['id']} | {v['pkg']} | {v['installed']} | {fixed} | {title} |")
                    lines.append("")

                if has_fix:
                    lines.append("## Remediation Plan")
                    lines.append("")
                    lines.append("Packages with available fixes — upgrade to the listed version:")
                    lines.append("")
                    seen = set()
                    for v in sorted(has_fix, key=lambda x: x["pkg"]):
                        key = (v["pkg"], v["fixed"])
                        if key not in seen:
                            seen.add(key)
                            lines.append(f"- `{v['pkg']}`: upgrade from `{v['installed']}` to `{v['fixed']}`")
                    lines.append("")

            with open(md_path, "w") as f:
                f.write("\n".join(lines) + "\n")

            print(f"Report written to {md_path}")
        volumeMounts:
          - name: workspace
            mountPath: /workspace
      outputs:
        artifacts:
          - name: report
            path: /workspace/src/docs/{{inputs.parameters.target}}-cve-remediation.md
            archive:
              none: {}

    # --- Commit Reports to Repo ---
    - name: commit-reports
      container:
        image: alpine/git:latest
        command: [sh, -c]
        args:
          - |
            cd /workspace/src
            git config user.email "ci@swish.local"
            git config user.name "Swish CI"
            git add docs/*-cve-remediation.md
            if git diff --cached --quiet; then
              echo "No report changes to commit."
              exit 0
            fi
            GIT_USER=$(cat /git-secret/username)
            GIT_PASS=$(cat /git-secret/password)
            git remote set-url origin https://${GIT_USER}:${GIT_PASS}@github.com/cthomaspdx/swish.git
            git commit -m "docs: update CVE remediation reports [skip ci]"
            git push origin HEAD:main
        volumeMounts:
          - name: workspace
            mountPath: /workspace
          - name: git-secret
            mountPath: /git-secret
            readOnly: true

    # --- Trigger Deploy via Argo Events webhook ---
    - name: trigger-deploy
      inputs:
        parameters:
          - name: target
      container:
        image: curlimages/curl:latest
        command: [curl]
        args:
          - -sf
          - -X
          - POST
          - -H
          - "Content-Type: application/json"
          - -d
          - "{}"
          - "http://webhook-eventsource-svc.argo-events.svc.cluster.local:12000/deploy/{{inputs.parameters.target}}"
