apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: swish-ci
  namespace: argo
spec:
  entrypoint: ci-pipeline
  arguments:
    parameters:
      - name: target
        value: all
        enum:
          - all
          - python3
          - python2
          - r
  volumes:
    - name: docker-config
      secret:
        secretName: dockerhub-credentials
        items:
          - key: .dockerconfigjson
            path: config.json
    - name: git-secret
      secret:
        secretName: github-credentials
    - name: workspace
      persistentVolumeClaim:
        claimName: swish-workspace

  templates:
    # --- Main DAG ---
    - name: ci-pipeline
      dag:
        tasks:
          - name: checkout
            template: git-checkout

          # Python 3: build → scan
          - name: build-python3
            template: build-and-push
            dependencies: [checkout]
            when: "'{{workflow.parameters.target}}' == 'all' || '{{workflow.parameters.target}}' == 'python3'"
            arguments:
              parameters:
                - name: image-name
                  value: swish-python3
                - name: context
                  value: docker/python3

          - name: scan-python3
            template: trivy-scan
            dependencies: [build-python3]
            when: "'{{workflow.parameters.target}}' == 'all' || '{{workflow.parameters.target}}' == 'python3'"
            arguments:
              parameters:
                - name: image
                  value: cthomaspdx1/swish-python3:latest

          # Python 2: build → scan
          - name: build-python2
            template: build-and-push
            dependencies: [checkout]
            when: "'{{workflow.parameters.target}}' == 'all' || '{{workflow.parameters.target}}' == 'python2'"
            arguments:
              parameters:
                - name: image-name
                  value: swish-python2
                - name: context
                  value: docker/python2

          - name: scan-python2
            template: trivy-scan
            dependencies: [build-python2]
            when: "'{{workflow.parameters.target}}' == 'all' || '{{workflow.parameters.target}}' == 'python2'"
            arguments:
              parameters:
                - name: image
                  value: cthomaspdx1/swish-python2:latest

          # R: build → scan
          - name: build-r
            template: build-and-push
            dependencies: [checkout]
            when: "'{{workflow.parameters.target}}' == 'all' || '{{workflow.parameters.target}}' == 'r'"
            arguments:
              parameters:
                - name: image-name
                  value: swish-r
                - name: context
                  value: docker/r

          - name: scan-r
            template: trivy-scan
            dependencies: [build-r]
            when: "'{{workflow.parameters.target}}' == 'all' || '{{workflow.parameters.target}}' == 'r'"
            arguments:
              parameters:
                - name: image
                  value: cthomaspdx1/swish-r:latest

          # Trigger ArgoCD refresh via Argo Events webhook
          - name: trigger-deploy
            template: trigger-deploy
            dependencies:
              - scan-python3
              - scan-python2
              - scan-r

    # --- Git Checkout ---
    - name: git-checkout
      container:
        image: alpine/git:latest
        command: [sh, -c]
        args:
          - |
            rm -rf /workspace/src
            GIT_USER=$(cat /git-secret/username)
            GIT_PASS=$(cat /git-secret/password)
            git clone https://${GIT_USER}:${GIT_PASS}@github.com/cthomaspdx/swish.git /workspace/src
        volumeMounts:
          - name: workspace
            mountPath: /workspace
          - name: git-secret
            mountPath: /git-secret
            readOnly: true

    # --- Build & Push ---
    - name: build-and-push
      inputs:
        parameters:
          - name: image-name
          - name: context
      container:
        image: gcr.io/kaniko-project/executor:latest
        args:
          - --context=/workspace/src/{{inputs.parameters.context}}
          - --destination=cthomaspdx1/{{inputs.parameters.image-name}}:latest
          - --cache=true
          - --cache-repo=cthomaspdx1/kaniko-cache
          - --single-snapshot
          - --compressed-caching=false
        resources:
          requests:
            memory: 2Gi
            cpu: 500m
          limits:
            memory: 4Gi
        volumeMounts:
          - name: workspace
            mountPath: /workspace
          - name: docker-config
            mountPath: /kaniko/.docker

    # --- Trivy Scan ---
    - name: trivy-scan
      inputs:
        parameters:
          - name: image
      container:
        image: aquasec/trivy:latest
        command: [trivy]
        args:
          - image
          - --severity
          - CRITICAL,HIGH
          - --exit-code
          - "0"
          - --format
          - table
          - "{{inputs.parameters.image}}"

    # --- Trigger Deploy via Argo Events webhook ---
    - name: trigger-deploy
      container:
        image: curlimages/curl:latest
        command: [curl]
        args:
          - -sf
          - -X
          - POST
          - -H
          - "Content-Type: application/json"
          - -d
          - "{}"
          - "http://webhook-eventsource-svc.argo-events.svc.cluster.local:12000/deploy"
