apiVersion: v1
kind: Secret
metadata:
  name: dockerhub-credentials
  namespace: argo
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "https://index.docker.io/v1/": {
          "username": "<YOUR_DOCKERHUB_USERNAME>",
          "password": "<YOUR_DOCKERHUB_PAT>"
        }
      }
    }
